---
# Tasks file for mp-env role
- name: install lxterminal if necessary
  pacman:
    name: lxterminal
    state: present
  when: ( system_type == "hybrid" ) or
        ( system_type == "gen" )

- name: create directory for lxterminal
  file:
    path: /home/{{ item.username }}/.config/lxterminal
    state: directory
    owner: "{{ item.username }}"
    group: "{{ item.group }}"
    mode: 0755
  when: ( system_type == "hybrid" ) or
        ( system_type == "gen" )
  with_items: "{{ users }}"

- name: copy lxterminal config files
  template:
    src: lxterminal.conf.j2
    dest: /home/{{ item.username }}/.config/lxterminal/lxterminal.conf
    owner: "{{ item.username }}"
    group: "{{ item.group }}"
    mode: 0600
  when: ( system_type == "hybrid" ) or
        ( system_type == "gen" )
  with_items: "{{ users }}"

- name: install compton
  pacman:
    name: compton
    state: present
  when: ( system_type == "hybrid" ) or
        ( system_type == "gen" )

- name: copy compton configs
  copy:
    src: compton.conf
    dest: /home/{{ item.username }}/.config/compton.conf
    owner: "{{ item.username }}"
    group: "{{ item.group }}"
    mode: 0644
  when: ( system_type == "gen" )
  with_items: "{{ users }}"

- name: install urxvt if necessary
  pacman:
    name: rxvt-unicode
    state: present
  when: ( system_type == "dev" )

- name: create Xresources directory
  file:
    path: /home/{{ item.username }}/.config/Xresources
    state: directory
    owner: "{{ item.username }}"
    group: "{{ item.group }}"
    mode: 0755
  when: ( system_type == "dev" ) or
        ( system_type == "hybrid" )
  with_items: "{{ users }}"

- name: copy dummy Xresources
  copy:
    src: Xresources
    dest: /home/{{ item.username }}/.Xresources
    owner: "{{ item.username }}"
    group: "{{ item.group }}"
    mode: 0644
  when: ( system_type == "dev" ) or
        ( system_type == "hybrid" )
  with_items: "{{ users }}"

- name: install rofi if necessary
  pacman:
    name: rofi
    state: present
  when: ( system_type == "dev" ) or
        ( system_type == "hybrid" )

- name: copy configs for rofi
  template:
    src: rofi.j2
    dest: /home/{{ item.username }}/.config/Xresources/rofi
    owner: "{{ item.username }}"
    group: "{{ item.group }}"
    mode: 0644
  when: ( system_type == "dev" ) or
        ( system_type == "hybrid" )
  with_items: "{{ users }}"

- name: copy config for urxvt
  copy:
    src: rxvt-unicode
    dest: /home/{{ item.username }}/.config/Xresources/rxvt-unicode
    owner: "{{ item.username }}"
    group: "{{ item.group }}"
    mode: 0644
  when: ( system_type == "dev" )

- name: create directory for bash configs
  file:
    path: /home/{{ item.username }}/.config/bash
    state: directory
    owner: "{{ item.username }}"
    group: "{{ item.group }}"
    mode: 0755
  with_items: "{{ users }}"

- name: copy dummy bashrc
  copy:
    src: bashrc
    dest: /home/{{ item.username }}/.bashrc
    owner: "{{ item.username }}"
    group: "{{ item.group }}"
    mode: 0644
  with_items: "{{ users }}"

- name: copy actual bashrc
  template:
    src: bashrc-real.j2
    dest: /home/{{ item.username }}/.config/bash/bashrc-real
    owner: "{{ item.username }}"
    group: "{{ item.group }}"
    mode: 0644
  with_items: "{{ users }}"

- name: copy inputrc
  copy:
    src: inputrc
    dest: /home/{{ item.username }}/.config/bash/inputrc
    owner: "{{ item.username }}"
    group: "{{ item.group }}"
    mode: 0644
  with_items: "{{ users }}"

- name: copy root bashrc
  copy:
    src: bashrc-root
    dest: /root/.bashrc
    owner: root
    group: root
    mode: 0644

- name: install archey3
  pacman:
    name: archey3
    state: present
  when: ( system_type == "gen" ) or
        ( system_type == "hybrid" )

- name: install screenfetch
  pacman:
    name: screenfetch
    state: present
  when: ( system_type == "dev" )
...
