---
# Full playbook

# This needs to happen before everything else
- hosts: all
  roles:
    - { role: pacman, tags: ['pacman', 'all'] }
  tasks:
    - include: includes/network_setup.yml
      tags: ['network', 'all']

- hosts: all
  tasks:
    - include: includes/install_xorg.yml
      tags: ['install_xorg', 'all']
    - include: includes/install_admin_tools.yml
      tags: ['install_admin_tools', 'all']
    - include: includes/install_fonts.yml
      tags: ['install_fonts', 'all']
  roles:
    - { role: users, tags: ['users', 'all'] }
    - { role: git, tags: ['git', 'all'] }
    - { role: lightdm, tags: ['lightdm', 'all'] }
    - { role: vim, tags: ['vim', 'all'] }
    - { role: music, tags: ['music', 'all'] }
    - { role: mp-env, tags: ['mp-env', 'all'] }

- hosts: general

- hosts: dev-ops
  roles:
    - { role: dunst, tags: ['dunst', 'dev-ops'] }

- hosts: general-purpose
  roles:
    - { role: openbox, tags: ['openbox', 'general-purpose'] }

- hosts: general-dev
  roles:
    - { role: i3, tags: ['i3', 'general-dev'] }

- hosts: development
  roles:
    - { role: spectrwm, tags: ['spectrwm', 'development'] }

- hosts: virtual
  roles:
    - { role: vboxguest, tags: ['vboxguest', 'virtual'] }
...
