---
# Full playbook

# This needs to happen before everything else
- hosts: all
  roles:
    - { role: pacman, tags: ['pacman', 'all'] }

- hosts: all
  tasks:
    - include: includes/install_xorg.yml
      tags: ['install_xorg', 'all']
    - include: includes/install_admin_tools.yml
      tags: ['install_admin_tools', 'all']
    - include: includes/install_fonts.yml
      tags: ['install_fonts', 'all']
  roles:
    - { role: users, tags: ['users', 'all'] }
    - { role: git, tags: ['git', 'all'] }
    - { role: lightdm, tags: ['lightdm', 'all'] }
    - { role: vim, tags: ['vim', 'all'] }
    - { role: music, tags: ['music', 'all'] }

- hosts: general

- hosts: dev-ops

- hosts: general-purpose

- hosts: general-dev

- hosts: development

...
