---
# tasks file for pacman
# Seems strange, but might as well copy sudoers file here
- name: copy sudoers file
  copy:
    src: sudoers
    dest: /etc/sudoers
    owner: root
    group: root
    mode: 0440

- name: copy antergos-keyring package
  copy:
    src: antergos-keyring-20150806-1-any.pkg.tar.xz
    dest: /var/antergos-keyring-20150806-1-any.pkg.tar.xz
    owner: root
    group: root
    mode: 0644

- name: install antergos-keyring package
  command: /usr/bin/pacman --noconfirm -U /var/antergos-keyring-20150806-1-any.pkg.tar.xz

- name: initialize pacman keyring
  command: /usr/bin/pacman-key --init archlinux antergos

- name: populate pacman keyring
  command: /usr/bin/pacman-key --populate archlinux antergos

- name: copy pacman config files
  copy:
    src: "{{ item.file }}"
    dest: "{{ item.dest }}"
    owner: root
    group: root
    mode: 0644
  with_items:
      - { file: pacman.conf, dest: /etc/pacman.conf }
      - { file: antergos-mirrorlist, dest: /etc/pacman.d/antergos-mirrorlist }

- name: refresh databases
  pacman: update_cache=yes
...
