---
# tasks file for users
- name: create groups
  group: name={{ item }}
  with_items: groups_to_create
  tags: [ 'groups' ]

- name: create per-user groups
  group: name={{ item.username }} gid={{ item.uid }}
  with_items: users
  tags: [ 'users', 'groups' ]

- name: create users
  user:
    name: "{{ item.username }}"
    group: "{{ item.username if users_create_per_user_group else item.group }}"
    groups: "{{ item.groups | join(',') }}"
    shell: "{{ item.shell if item.shell is defined else users_default_shell }}"
    comment: "{{ item.name }}"
    uid: "{{ item.uid }}"
    createhome: "{{ 'yes' if users_create_homedirs else 'no' }}"
  with_items: users
  tags: [ 'users' ]

- name: deleted user removal
  user: 
    name: "{{item.username}}" 
    state: absent
  with_items: users_deleted
  tags: [ 'users', 'configuration' ]

- name: deleted per-user group removal
  group: 
    name: "{{ item.username }}"
    state: absent
  with_items: users_deleted
  when: users_create_per_user_group
  tags: [ 'users' ]

- name: create user directories
  file:
    path: "/home/{{ item[0].username }}/{{ item[1] }}"
    state: directory
    owner: "{{ item[0].username }}"
    group: "{{ item[0].username if users_create_per_user_group else users_group }}"
  with_nested:
    - users
    - "{{ users_dirs }}"
  tags: [ 'users' ]

- name: set default password
  shell: echo "{{ item.username }}":default | chpasswd
  with_items:
    - users

- name: enforce password change next login
  command: /usr/bin/chage -d 0 "{{ item.username }}"
  with_items:
    - users
...
